//Generated by Ruloir, version <%=::Ruloir::VERISON%>
#include <ruloir-prefix.h>
#define WriteConstStr(handle,str)	BufferedWrite(handle,str,(sizeof(str)/sizeof(char))-1)
#define WRITE_BUFFER_LENGTH 4096

typedef struct WriteBuffer{
	int fd;
	size_t len;
	char buf[WRITE_BUFFER_LENGTH];
} WriteBuffer;

void* AppCreateHandle(){
	return malloc(sizeof(WriteBuffer));
}
void AppDestroyHandle(void* handle){
	free(handle);
}

void BufferFlush(void* handle){
	WriteBuffer *self=(WriteBuffer*)handle;
	while(self->len>0)
		self->len-=write(self->fd, self->buf, self->len);
}
void BufferedWrite(void* handle, const void* data, size_t len){
	while(len>0){
		WriteBuffer *self=(WriteBuffer*)handle;
		size_t remaining=WRITE_BUFFER_LENGTH-self->len;
		if(remaining>=len){
			memcpy(self->buf+self->len, data, len);
			self->len+=len;
			return;
		}else{
			memcpy(self->buf+self->len, data, remaining);
			BufferFlush(handle);
			len-=remaining;
		}
	}
}

<%=before%>

void AppFunc(
	void* handle,
	void* cache,
	int fd,
	const char *method,
	const char *path,
	void (*ChunkGet)(void *cache,const char *key_a,const char *key_b,const char **ptr,int *len),
	bool (*ChunkExists)(void* cache,const char *key)
){
	handle->fd=fd;
	handle->len=0;
	
	<%=selector%>
	
	BufferFlush(handle);
}